server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.10.237:1521:HYYC
    username: hyadmin
    password: hy237
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j

dubbo:
  zookeeper:
    address: 192.168.10.60:2181
  interface:
    version: 0.4.1

logging:
  home: E:/meet-log